server:
  port: 8081

spring:
  application:
    name: mall_product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.85.113.163:3306/pay?serverTimezone=Asia/Shanghai
    username: root
    password: Imc@124!
    hikari:
      minimum-idle: 5 # ??????????????10
      idle-timeout: 600000 # ????
      maximum-pool-size: 10 # ??????????????????????
      auto-commit: true # ?????????????
      pool-name: myHikariCP # ??????
      max-lifetime: 1800000 # ?????????????
      connection-timeout: 30000 # ?????????30s
      connection-test-query: select 1
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/pay?serverTimezone=Asia/Shanghai
#    username: root
#    password: ahui940722
