server:
  port: 8080

spring:
  application:
    name: mall_product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.85.113.163:3306/one_mall?serverTimezone=Asia/Shanghai
    username: root
    password: Imc@124!
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/one_mall?serverTimezone=Asia/Shanghai
#    username: root
#    password: ahui940722


